### ISSUE TITLE
updates & access

### ISSUE THREAD

**Issue by geemus** [fog/fog-brightbox#39]
Hey, I'm trying to roll through and update fog-core versions to 2.0+, but I just realized I don't have access to push this gem. Could you give me access? Also, if you have time to help update to new fog-core and test that would be most helpful, thanks!

**Comment by tokengeek** [comment]
@geemus - You should have access already as a member of the @fog/fog-brightbox group.

**Comment by geemus** [comment]
@tokengeek sorry, let me further clarify. I have fine access to the github repo, but no push access for the rubygem itself. Does that make more sense?

**Comment by tokengeek** [comment]
@geemus Ah, okay. Skim-read and missed the "gem" keyword.

I've added you as an owner to the `fog-brightbox` gem now.

**Comment by geemus** [comment]
no worries, thanks for the quick response!
